config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :managers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope "(:locale)", locale: /en|vi/ do
    # root "students#index"
    resources :managers
  end
  mount ActionCable.server => '/cable'
  get "/" => redirect("/student/login")
  namespace :manager do
    get "/" => redirect("/manager/students-arrangement")

    get "/login", to: "manager_sessions#new"
    post "/login", to: "manager_sessions#create"
    get "/logout", to: "manager_sessions#destroy"
    get "/students-arrangement", to: "students_arrangement#main"

    get "/service-management", to: "service_management#index"
    post "/service-management/:id/:year/:month", to: "service_management#show_service_charge"
    post "/service-management/:id/:year/:month/update", to: "service_management#update_service_charge"
    # get "/service-management/find", to: "service_management#find_service_chare"
    get "/service-management/filter", to: "service_management#filter"
    post "/service-management/remind", to: "service_management#remind"
    post "/service-management/import", to: "service_management#import"
    delete "/service-management/delete", to: "service_management#delete"


    get "/post-management", to: "post_management#index"
    get "/post-management/show", to: "post_management#show"
    post "/post-management/create", to: "post_management#create"
    put "/post-management/update", to: "post_management#update"
    post "/post-management/", to: "post_management#change_post_status"
    post "/post-management/restore", to: "post_management#restore"
    get "/post-management/find-post", to: "post_management#find_post"
    get "/post-management/:id", to: "post_management#show"


    get "/student-management", to: "student_management#index"
    put "/student-management/reset-ava", to: "student_management#reset_ava"
    post "/student-management/:id/update-avatar", to: "student_management#update_avatar"
    get "/student-management/search-students", to: "student_management#search_student"
    get "/student-management/:id/show", to: "student_management#show"
    post "/student-management/create-member", to: "student_management#create_room_member"
    post "/student-management/create", to: "student_management#create"
    get  "/student-management/:id/edit", to: "student_management#edit"
    get  "/student-management/pending-students", to: "student_management#find_pending_student"
    get  "/student-management/:id", to: "student_management#edit"
    patch  "/student-management/:id/update", to: "student_management#update"
    delete  "/student-management/:id/delete", to: "student_management#destroy"
    post "/student-management/checkduplicate", to: "student_management#check_duplicate_student"
    post "/student-management/checkduplicate-informations", to: "student_management#check_duplicate_informations"
    # get "/student-management/find-student", to: "student_management#find_student"
    
    get "/room-management/", to: "room_management#index"
    get "/room-management/rooms/:room_id/active_room", to: "room_management#active_room"
    get "/room-management/rooms/:room_id/members", to: "room_management#show_room_members"
    get "/room-management/rooms/:room_id/facilities", to: "room_management#show_room_facilities"
    get "/room-management/rooms/:room_id/service-charges", to: "room_management#show_room_service_charges"
    get "/room-management/rooms/:room_id/informations", to: "room_management#show_room_informations"
    put "/room_management/:id/update", to: "room_management#update"
    post "/room-management/checkduplicate", to: "room_management#check_duplicate_room"
    get "/room-management/rooms/:room_id", to: "room_management#show_room_informations"
    get "/homepage/", to: "homepage_management#index"
    get "/posts/:id", to: "homepage_management#show"
    post "/room-management/create", to: "room_management#create"
    post "/room-management/rooms/:room_id/service-charge/:year/:month", to: "service_management#show_service_charge"
    post "/room-management/rooms/:room_id/service-charge/:year/:month/update", to: "service_management#update_room_service_charge"
    get "/room-management/find-room", to: "room_management#find_room"
    get "/room-management/:id/number-student", to: "room_management#room_number_student"
    post "/room-management/validation", to: "room_management#check_room_max_number_student_validation"

    post "/facility-management/create", to: "facility_management#create"
    put "/facility-management/:id/update", to: "facility_management#update"
    post "/facility-management/:id/delete", to: "facility_management#destroy"
    get "/facility-management/:id", to: "facility_management#show"

    post "/students-arrangement/remove-student", to: "students_arrangement#remove_student_from_room"
    post "/students-arrangement/add-student", to: "students_arrangement#add_student_to_room"
    get "/students-arrangement/all-rooms-arrangement", to: "students_arrangement#search_rooms_arrangement"
    get "/students-arrangement/all-pending-students-arrangement", to: "students_arrangement#search_pending_students_arrangement"

    get "/managers/search", to: "managers#search_student_and_room"

    get "/report-management/", to: "report_management#pending_complaint_report"
    get "/report-management/complaint-reports", to: "report_management#pending_complaint_report"
    get "/report-management/complaint-reports/pending", to: "report_management#pending_complaint_report"
    get "/report-management/complaint-reports/approved", to: "report_management#approved_complaint_report"
    get "/report-management/complaint-reports/rejected", to: "report_management#rejected_complaint_report"
    get "/report-management/complaint-reports/find-by-status", to: "report_management#find_complaint_report_by_status"
    get "/report-management/complaint-reports/:id", to: "report_management#show_complaint_report" 
    put "/report-management/complaint-reports/:id/reject", to: "report_management#deny_complaint_report"
    put "/report-management/complaint-reports/:id/approve", to: "report_management#approve_complaint_report"

    get "/report-management/facility-reports", to: "report_management#pending_facility_report"
    get "/report-management/facility-reports/pending", to: "report_management#pending_facility_report"
    get "/report-management/facility-reports/approved", to: "report_management#approved_facility_report"
    get "/report-management/facility-reports/rejected", to: "report_management#rejected_facility_report"
    get "/report-management/facility-reports/find-by-status", to: "report_management#find_facility_report_by_status"
    get "/report-management/facility-reports/:id", to: "report_management#show_facility_report"
    put "/report-management/facility-reports/:id/reject", to: "report_management#reject_facility_report"
    put "/report-management/facility-reports/:id/approve", to: "report_management#approve_facility_report"

    get "/report-management/form-requests", to: "report_management#pending_form_request"
    get "/report-management/form-requests/pending", to: "report_management#pending_form_request"
    get "/report-management/form-requests/approved", to: "report_management#approved_form_request"
    get "/report-management/form-requests/rejected", to: "report_management#rejected_form_request"
    get "/report-management/form-requests/find-by-status", to: "report_management#find_form_request_by_status"
    get "/report-management/form-requests/:id", to: "report_management#show_form_request"
    put "/report-management/form-requests/:id/reject", to: "report_management#reject_form_request"
    put "/report-management/form-requests/:id/approve", to: "report_management#approve_form_request"

    get "/building-management/", to: "building_management#index"
    get "/building-management/:id", to: "building_management#show"

      
    post "/reset-password", to: "reset_password_manager#reset_manager_password"
    get "/reset-password/edit", to: "reset_password_manager#edit_manager_password"
    post "/reset-password/update", to: "reset_password_manager#update_manager_password"

    
    resources :students
    resources :managers
    resources :rooms
  end
  
  namespace :student do
    get "/" => redirect("/student/my-profile")
    
    get "/login", to: "student_sessions#new"
    post "/login", to: "student_sessions#create"
    get "/logout", to: "student_sessions#destroy"
    get "/requests", to: "complaint_reports#index"
    
    get "/requests/facility", to: "facility_reports#index"
    get "/requests/facility/:id", to: "facility_reports#show"
    post "/facility-reports/create", to: "facility_reports#create"
    
    get "/requests/form", to: "form_requests#index"
    get "/requests/form/:id", to: "form_requests#show"
    post "/requests/form/create", to: "form_requests#create"
    
    get "/requests/complaint", to: "complaint_reports#index"
    get "/requests/complaint/:id", to: "complaint_reports#show"
    post "/complaint-reports/create", to: "complaint_reports#create"
    
    get "/room/member/show/", to: "rooms#show_member"
    
    post "/student-profile/update-avatar/", to: "student_profiles#update_avatar"
    put "/student-profile/reset-ava", to:"student_profiles#reset_ava"
    put "/student-profile/update", to:"student_profiles#update"
    put "/student-profile/reset-password", to:"student_profiles#reset_password"
    
    get "/my-room/", to: "rooms#room_member"
    get "/my-room/members", to: "rooms#room_member"
    get "/my-room/services", to: "rooms#room_service_charge"

    post "/reset-password", to: "reset_password_student#reset_student_password"
    get "/reset-password/edit", to: "reset_password_student#edit_student_password"
    post "/reset-password/update", to: "reset_password_student#update_student_password"

    get "/homepage/", to: "homepage#index"

app/views/layouts/student_layout/_header.html.erb
  <div class="student_header">
    <div class="ui secondary pointing menu">
    <% if logged_in_student? %>
      <%= link_to student_homepage_path, class: "item", id: "manager_home_path", data: { turbolinks: false } do %>
        <img src="/assets/custom_logo2.png" style="width: 14rem"/>
      <% end %>
    <% end %>
      <div class="right menu">
        <% if logged_in_student? %>
          <input type="hidden" name="current_channel" id="current_channel" value="<%= current_user.channel%>">
          <%= link_to "Thông tin cá nhân", "/student/my-profile/", class: "item", id: "student_student_profiles_path", data: { turbolinks: false } %>
          <%= link_to "Phòng của tôi", "/student/my-room", class: "item", id: "student_room_path", data: { turbolinks: false } %>
          <%= link_to "Báo cáo", student_requests_path, class: "item", id: "student_requests_path", data: { turbolinks: false } %>
          <div class="ui floating labeled icon dropdown button" style="position: relative; background-color: #ffffff" id="noti_button" >
            <img src="/assets/bell.png" style="width: 1.5rem; height: 1.5rem; position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%)" onclick="showNotiList()"/>
            <div id="unread" class="floating ui red label" style="display: none; top: 0.5rem; left: 1.5rem; padding: 0.3rem; border-radius: 0.2rem;"><%= current_user.notifications.where(is_read: 'false').count %></div>
            <div class="ui menu">
              <h3 style="margin: 1rem;">Thông báo</h3>
              <div id="list_noti" style="max-height: 30rem; overflow: auto;">
                <% if current_user.notifications.length > 0 %>
                  <% current_user.notifications.order('created_at DESC').each do |notification| %>
                    <% if notification.is_read %>
                      <div class="item noti_item" style="width: 20rem; max-height: 11.5rem; overflow: hidden; display: block">
                        <div onclick="readNotification(<%= notification.id %>, '<%= notification.noti_type %>', <%= notification.report_id || 0 %>, <%= notification.page || 0 %>)" style= "width: 17rem; overflow: hidden;text-overflow: ellipsis;word-wrap: break-word;-webkit-line-clamp: 2;-webkit-box-orient: vertical;line-height: 2.25rem;  white-space: pre-wrap;"><%= notification.message %></div>
                        <p style="font-size: 0.7rem; color: #b8b8b8"><%= time_ago(notification.created_at) %></p>
                      </div>
                    <% else %>
                      <div class="item noti_item" style="width: 20rem; max-height: 11.5rem; overflow: hidden; display: block; background-color: #e0e0e0">
                        <div onclick="readNotification(<%= notification.id %>, '<%= notification.noti_type %>', <%= notification.report_id || 0 %>, <%= notification.page || 0 %>)" style= "width: 17rem; overflow: hidden;text-overflow: ellipsis;word-wrap: break-word;-webkit-line-clamp: 2;-webkit-box-orient: vertical;line-height: 2.25rem;  white-space: pre-wrap;"><%= notification.message %></div>
                        <p style="font-size: 0.7rem; color: #b8b8b8"><%= time_ago(notification.created_at) %></p>
                      </div>
                    <% end %>
                    
                  <% end %>
                <% elsif current_user.notifications.length == 0 %>
                  <div class="item noti_item" style="width: 20rem; height: 4.5rem" id="no_notification">
                    <div class="" style= "width: 17rem; height: 4.5rem; overflow: hidden;text-overflow: ellipsis;word-wrap: break-word;-webkit-line-clamp: 2;-webkit-box-orient: vertical;line-height: 2.25rem;  white-space: pre-wrap; display: flex; align-items: center">Không có thông báo</div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        <% else %>
          <%= link_to "Đăng nhập", student_login_path, class: "item", id: "student_login_path", data: { turbolinks: false } %>
        <% end %>
        <% if logged_in_student? %>
        <div class="item" style="height: 100%">
          <%= current_user.name %>
        </div>
          
        <% end %>
        <% if logged_in_student? %>
          <%= link_to "Đăng xuất", student_logout_path, class: "item", data: { turbolinks: false } %>
        <% end %>
      </div>
    </div>
  </div>
<script>
  $(document).on('click', '#language_dropdown', function(){
    $('#language_dropdown').dropdown('show');
  });
  const current_url = window.location.pathname
  if (current_url.indexOf("/student/requests") != -1) {
    $("#student_requests_path").addClass("active");
  }
  if (current_url.indexOf("/student/my-room") != -1) {
    $("#student_room_path").addClass("active");
  }
  else if (current_url.indexOf("/student/my-profile") != -1){
    $("#student_student_profiles_path").addClass("active");
  }
  else if (current_url.indexOf("students") != -1){
    $("#home_path").addClass("active");
  }
    
  function showNotiList(){
    $('#noti_button').dropdown();
  }
</script>
<script src="https://js.pusher.com/7.0/pusher.min.js"></script>
<script>
//hiển thị số lượng tb chưa đọc, nếu = 0 thì k hiển thị
    $.ajax({
      type: 'GET',
      url: '/notifications/unread',
      success: function(result){
        if(result.unread == 0) {
          $("#unread").hide()
        } else {
          $("#unread").show()
        }
      }, 
      error: function (error) {

      }
    })

    let current_channel = document.querySelector("#current_channel").value;
    Pusher.logToConsole = true;
    //kết nối topiws server của pusher
    var pusher = new Pusher('29056021d38b15b42578', {
      cluster: 'ap1',
      encrypted: true
    });

    var channel = pusher.subscribe(current_channel);
    channel.bind('new', function(data){
      if (data.notification.is_read) {
        $('#list_noti').prepend(`<div class="item noti_item" style="width: 20rem; max-height: 11.5rem; overflow: hidden; display: block; background-color: #e0e0e0">
                                <div onclick="readNotification(${data.notification.id}, '${data.notification.noti_type}', ${data.notification.report_id || 0}, ${data.notification.page || 0})" style= "width: 17rem; overflow: hidden;text-overflow: ellipsis;word-wrap: break-word;-webkit-line-clamp: 2;-webkit-box-orient: vertical;line-height: 2.25rem;  white-space: pre-wrap; display: flex; align-items: center">${data.notification.message}</div>
                                <p style="font-size: 0.7rem; color: #b8b8b8">Vừa xong</p>
                              </div>`)
      } else {
        $('#list_noti').prepend(`<div class="item noti_item" style="width: 20rem; max-height: 11.5rem; overflow: hidden; display: block; background-color: #e0e0e0">
                                <div onclick="readNotification(${data.notification.id}, '${data.notification.noti_type}', ${data.notification.report_id || 0}, ${data.notification.page || 0})" style= "width: 17rem; overflow: hidden;text-overflow: ellipsis;word-wrap: break-word;-webkit-line-clamp: 2;-webkit-box-orient: vertical;line-height: 2.25rem;  white-space: pre-wrap; display: flex; align-items: center">${data.notification.message}</div>
                                <p style="font-size: 0.7rem; color: #b8b8b8">Vừa xong</p>
                              </div>`)
      }
      
      $("#no_notification").remove();
      //cập nhậtk lại số luọng tbao chuq đoc
      $.ajax({
        type: 'GET',
        url: '/notifications/unread',
        success: function(result){
          if (result.unread == 0) {
            $("#unread").hide()
          } else {
            $("#unread").show()
          }
          $("#unread").html(result.unread)
        }, 
        error: function (error) {

        }
      })
    });
    function readNotification(noti_id, noti_type, report_id, page) {
      // $(item).css("background-color", "white");
      let redirect_url = ''
      if (noti_type == "complaint_report") {
        redirect_url = `/student/requests/complaint?focus_id=${report_id}&page=${page}`
      } else if (noti_type == "facility_report") {
        redirect_url = `/student/requests/facility?focus_id=${report_id}&page=${page}`
      } else if (noti_type == "form_request") {
        redirect_url = `/student/requests/form?focus_id=${report_id}&page=${page}`
      } else if (noti_type == "add_student_to_room" || noti_type == "remove_student_from_room") {
        redirect_url = `/student/my-room`
      }
      else if (noti_type == "service_charge_remind") {
        redirect_url = `/student/my-room/services`
      }
      $.ajax({
        type: "PUT",
        url: `/notifications/${noti_id}/read`,
        success: function(result){
          window.location = redirect_url
        },
        error: function (error) {
          toastr.error('Xin lỗi, chức năng đọc thông báo đang được bảo trì! Vui lòng truy cập bằng cách khác!')
        }
      })
      
    }    
</script>
<style>
  .active.selected {
    font-weight: normal !important;
    border: none !important;
  }

  .noti_item{
    cursor: pointer;
  }
  .noti_item:hover {
    background-color: #e8e8e8 !important;
  }
</style>

app/views/layouts/student_layout/student.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%# <title>HCMADormitoryManagementSystem</title> %>
    <title><%= yield :title %> | Ký túc xá Học viên Chính trị Quốc gia Hồ Chí Minh</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= custom_bootstrap_flash %>
    <%# <link href= "https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" rel="stylesheet" />  %>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"
      integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
      crossorigin="anonymous"> 
    </script> 
    <script src= "https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel='icon' href='/assets/hcma logo.png' />
  </head>

  <body>
    <div class="student_layout">
      <%= render "layouts/student_layout/header" %>
      <div style="margin-top: 4rem;">
        <%= yield %>
      </div>
    </div>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.js"></script>
  <script>
    if(localStorage.getItem('login_successful')) {
      toastr.success(localStorage.getItem('login_successful'))
      localStorage.removeItem('login_successful')
    }
  </script>
</html>